#!/usr/bin/env bash
# generate-workstate.sh
#
# Produce a *mechanical* snapshot of the repository's current state, independent
# of any conversation memory. This is the ground truth that a takeover profile
# can trust even if the handoff prose is stale.
#
# Writes into .claude/ccp/handoff/:
#   WORKSTATE.md       - human-readable summary (redacted)
#   GIT_STATUS.txt     - git status --porcelain=v1 -b (redacted)
#   DIFF.patch         - full unstaged+staged diff (redacted)
#   RECENT_COMMITS.txt - last 20 commits, one line each
#
# All captured output is piped through redact-sensitive-output.sh so we never
# persist a token that happened to be sitting in a working-tree file.
#
# Safe to run from anywhere; it locates the repo root via git. If not a git
# repo, it still records pwd and notes the absence of git.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REDACT="$SCRIPT_DIR/redact-sensitive-output.sh"

# Fallback no-op redactor if the helper is missing for some reason.
redact() {
  if [[ -x "$REDACT" ]]; then
    "$REDACT"
  else
    cat
  fi
}

OUT_DIR=".claude/ccp/handoff"
mkdir -p "$OUT_DIR"

PWD_NOW="$(pwd)"
IS_GIT="no"
BRANCH="(none)"
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  IS_GIT="yes"
  BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '(detached)')"
fi

# --- Detect build/test commands (best effort, non-authoritative) ---
detect_commands() {
  local found=0
  if [[ -f package.json ]]; then
    echo "- Node project detected (package.json). Try: npm test / npm run build"
    found=1
  fi
  if [[ -f Makefile ]]; then
    echo "- Makefile detected. Try: make / make test"
    found=1
  fi
  if [[ -f pyproject.toml || -f setup.py || -f requirements.txt ]]; then
    echo "- Python project detected. Try: pytest / python -m pytest"
    found=1
  fi
  if [[ -f Cargo.toml ]]; then
    echo "- Rust project detected. Try: cargo test / cargo build"
    found=1
  fi
  if [[ -f go.mod ]]; then
    echo "- Go project detected. Try: go test ./... / go build ./..."
    found=1
  fi
  if [[ "$found" -eq 0 ]]; then
    echo "- No common build/test manifest detected. Ask the previous session."
  fi
}

# --- Raw artifacts (each redacted) ---
if [[ "$IS_GIT" == "yes" ]]; then
  git status --porcelain=v1 -b 2>&1 | redact > "$OUT_DIR/GIT_STATUS.txt" || true
  { git diff 2>/dev/null; git diff --staged 2>/dev/null; } | redact > "$OUT_DIR/DIFF.patch" || true
  git log --oneline -n 20 2>&1 | redact > "$OUT_DIR/RECENT_COMMITS.txt" || true
else
  echo "(not a git repository)" > "$OUT_DIR/GIT_STATUS.txt"
  echo "(not a git repository)" > "$OUT_DIR/DIFF.patch"
  echo "(not a git repository)" > "$OUT_DIR/RECENT_COMMITS.txt"
fi

# --- Human-readable WORKSTATE.md ---
{
  echo "# WORKSTATE"
  echo
  echo "_Mechanical repository snapshot generated by CCP. Secrets redacted._"
  echo
  echo "- Generated by: \`generate-workstate.sh\`"
  echo "- Working directory: \`$PWD_NOW\`"
  echo "- Git repository: $IS_GIT"
  echo "- Current branch: \`$BRANCH\`"
  echo
  echo "## git status"
  echo
  echo '```'
  cat "$OUT_DIR/GIT_STATUS.txt"
  echo '```'
  echo
  echo "## git diff --stat"
  echo
  echo '```'
  if [[ "$IS_GIT" == "yes" ]]; then
    { git diff --stat 2>/dev/null; git diff --staged --stat 2>/dev/null; } | redact || true
  else
    echo "(not a git repository)"
  fi
  echo '```'
  echo
  echo "## Recent commits"
  echo
  echo '```'
  cat "$OUT_DIR/RECENT_COMMITS.txt"
  echo '```'
  echo
  echo "## Detected build/test commands"
  echo
  detect_commands
  echo
  echo "## Full diff"
  echo
  echo "See \`DIFF.patch\` in this directory (redacted)."
} > "$OUT_DIR/WORKSTATE.md"

echo "Wrote workstate artifacts to $OUT_DIR/"
echo "  - WORKSTATE.md"
echo "  - GIT_STATUS.txt"
echo "  - DIFF.patch"
echo "  - RECENT_COMMITS.txt"
