#!/usr/bin/env bash
# plugin-inventory.sh
#
# Inventory the plugins visible to each Claude profile launcher and produce a
# side-by-side markdown report. This NEVER installs, enables, or modifies
# anything — it only reads.
#
# It assumes two launcher commands exist in PATH:
#   claude-team  -> Teams / work account
#   claude-max   -> personal Max account
#
# If a launcher is missing or its `plugin list` fails, we capture that safely
# and keep going so one broken profile doesn't blank out the whole report.
#
# Writes into .claude/ccp/plugins/:
#   team-plugins.txt      - raw (redacted) output of `claude-team plugin list`
#   max-plugins.txt       - raw (redacted) output of `claude-max plugin list`
#   PLUGIN_INVENTORY.md   - human-readable comparison

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REDACT="$SCRIPT_DIR/redact-sensitive-output.sh"
redact() { if [[ -x "$REDACT" ]]; then "$REDACT"; else cat; fi; }

OUT_DIR=".claude/ccp/plugins"
mkdir -p "$OUT_DIR"

TEAM_RAW="$OUT_DIR/team-plugins.txt"
MAX_RAW="$OUT_DIR/max-plugins.txt"
REPORT="$OUT_DIR/PLUGIN_INVENTORY.md"

# Capture `<launcher> plugin list` into a file, redacted. Records the failure
# inline instead of aborting. Echoes "ok" or "fail" on stdout for the caller.
capture_list() {
  local launcher="$1"
  local out_file="$2"
  if ! command -v "$launcher" >/dev/null 2>&1; then
    {
      echo "# CCP: launcher '$launcher' not found in PATH."
      echo "# Run /ccp:profile-doctor to diagnose."
    } > "$out_file"
    echo "fail"
    return 0
  fi
  # Combine stdout+stderr so we keep any useful diagnostics, then redact.
  if "$launcher" plugin list >"$out_file.tmp" 2>&1; then
    redact < "$out_file.tmp" > "$out_file"
    rm -f "$out_file.tmp"
    echo "ok"
  else
    {
      echo "# CCP: '$launcher plugin list' exited non-zero. Captured output below."
      redact < "$out_file.tmp"
    } > "$out_file"
    rm -f "$out_file.tmp"
    echo "fail"
  fi
}

TEAM_STATUS="$(capture_list claude-team "$TEAM_RAW")"
MAX_STATUS="$(capture_list claude-max "$MAX_RAW")"

# Extract a rough set of plugin "names" from a raw list file. Output formats
# vary across Claude Code versions, so this is best-effort: we pull the first
# token of lines that look like list entries and drop obvious noise. The raw
# files remain the source of truth.
extract_names() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  grep -Ev '^\s*#' "$f" \
    | grep -Ev '^\s*$' \
    | sed -E 's/^[[:space:]]*[-*•][[:space:]]+//' \
    | awk '{print $1}' \
    | grep -Ev '^(No|Plugins?|NAME|Name|Available|Installed|----|===)' \
    | sed -E 's/[:,]+$//' \
    | sort -u
}

TEAM_NAMES="$(extract_names "$TEAM_RAW")"
MAX_NAMES="$(extract_names "$MAX_RAW")"

only_team="$(comm -23 <(printf '%s\n' "$TEAM_NAMES") <(printf '%s\n' "$MAX_NAMES") 2>/dev/null | sed '/^$/d')"
only_max="$(comm -13 <(printf '%s\n' "$TEAM_NAMES") <(printf '%s\n' "$MAX_NAMES") 2>/dev/null | sed '/^$/d')"
common="$(comm -12 <(printf '%s\n' "$TEAM_NAMES") <(printf '%s\n' "$MAX_NAMES") 2>/dev/null | sed '/^$/d')"

list_or_none() { local v="$1"; if [[ -n "$v" ]]; then printf '%s\n' "$v" | sed 's/^/- /'; else echo "- (none)"; fi; }

{
  echo "# PLUGIN INVENTORY"
  echo
  echo "_Read-only comparison of plugins visible to each profile. CCP installs nothing here._"
  echo
  echo "- \`claude-team plugin list\`: **$TEAM_STATUS**"
  echo "- \`claude-max plugin list\`: **$MAX_STATUS**"
  echo
  echo "> Name extraction is best-effort because \`plugin list\` output varies by"
  echo "> Claude Code version. Treat \`team-plugins.txt\` and \`max-plugins.txt\` as"
  echo "> the authoritative captures; the lists below are a convenience diff."
  echo
  echo "## Only in Team (claude-team)"
  echo
  list_or_none "$only_team"
  echo
  echo "## Only in Max (claude-max)"
  echo
  list_or_none "$only_max"
  echo
  echo "## Common to both"
  echo
  list_or_none "$common"
  echo
  echo "## Enabled / disabled status and scope"
  echo
  echo "If the raw captures include enabled/disabled or scope columns, they are"
  echo "preserved verbatim (redacted) in the raw files. CCP does not infer these"
  echo "when they are absent."
  echo
  echo "## Recommended action"
  echo
  echo "1. Review \`team-plugins.txt\` and \`max-plugins.txt\`."
  echo "2. Run \`/ccp:plugin-export\` to capture the desired set into \`PLUGINS.lock.json\`."
  echo "3. Run \`/ccp:plugin-sync-plan\` to generate reviewable install scripts."
  echo "4. Review those scripts, then \`/ccp:plugin-apply\` for the target profile."
  echo
  echo "---"
  echo "_Generated by \`plugin-inventory.sh\`. No plugins were installed or modified._"
} > "$REPORT"

echo "Wrote plugin inventory to $OUT_DIR/"
echo "  - team-plugins.txt ($TEAM_STATUS)"
echo "  - max-plugins.txt ($MAX_STATUS)"
echo "  - PLUGIN_INVENTORY.md"
