#!/usr/bin/env bash
# profile-doctor.sh
#
# Diagnose the Claude profile setup so handoff/takeover and plugin sync don't
# fail in confusing ways later. Read-only. It checks that the launchers exist,
# that no environment override is silently redirecting auth to a different
# backend, and that CCP's repo-local state directory is usable.
#
# Crucially: it reports whether sensitive env vars are *present*, never their
# values. Knowing ANTHROPIC_API_KEY is set is the diagnostic signal; printing
# it would be exactly the leak CCP exists to avoid.
#
# Writes: .claude/ccp/PROFILE_DOCTOR.md

set -uo pipefail

OUT_DIR=".claude/ccp"
mkdir -p "$OUT_DIR"
REPORT="$OUT_DIR/PROFILE_DOCTOR.md"

# Check a launcher: report presence, path, and --version if it answers quickly.
check_launcher() {
  local name="$1"
  if command -v "$name" >/dev/null 2>&1; then
    local path ver
    path="$(command -v "$name")"
    ver="$("$name" --version 2>/dev/null | head -1 || true)"
    [[ -z "$ver" ]] && ver="(no --version output)"
    echo "- \`$name\`: **found** at \`$path\` — version: $ver"
  else
    echo "- \`$name\`: **NOT found** in PATH"
  fi
}

# Report only presence of a sensitive env var, never the value.
check_env_present() {
  local var="$1"
  if [[ -n "${!var:-}" ]]; then
    echo "- \`$var\`: **SET** (value hidden). If unintended, unset it before switching profiles."
  else
    echo "- \`$var\`: not set"
  fi
}

is_git="no"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 && is_git="yes"

# Probe whether CCP can create its state dir.
ccp_writable="no"
if mkdir -p "$OUT_DIR/.write-probe" 2>/dev/null; then
  rmdir "$OUT_DIR/.write-probe" 2>/dev/null || true
  ccp_writable="yes"
fi

{
  echo "# PROFILE DOCTOR"
  echo
  echo "_CCP environment diagnosis. Read-only. No secret values are shown._"
  echo
  echo "## Launchers"
  echo
  check_launcher "claude"
  check_launcher "claude-team"
  check_launcher "claude-max"
  echo
  echo "## Environment overrides (presence only)"
  echo
  echo "These variables can silently redirect Claude Code to a different account"
  echo "or backend. For normal profile switching they should usually be unset."
  echo
  check_env_present "ANTHROPIC_API_KEY"
  check_env_present "ANTHROPIC_AUTH_TOKEN"
  check_env_present "CLAUDE_CODE_USE_BEDROCK"
  check_env_present "CLAUDE_CODE_USE_VERTEX"
  check_env_present "CLAUDE_CODE_USE_FOUNDRY"
  echo
  echo "## Context"
  echo
  echo "- Working directory: \`$(pwd)\`"
  echo "- Inside a git repository: $is_git"
  if [[ -n "${CLAUDE_PLUGIN_ROOT:-}" && -d "${CLAUDE_PLUGIN_ROOT}" ]]; then
    echo "- CCP plugin loaded: yes (running from an installed plugin)"
  elif [[ -n "${CLAUDE_PLUGIN_ROOT:-}" ]]; then
    echo "- CCP plugin loaded: \`CLAUDE_PLUGIN_ROOT\` set but path missing — reinstall / \`/reload-plugins\`"
  else
    echo "- CCP plugin loaded: \`CLAUDE_PLUGIN_ROOT\` not set (script run directly, not via an installed plugin)"
  fi
  echo "- CCP state dir \`.claude/ccp\` writable: $ccp_writable"
  echo
  echo "## Profile config directories (best effort)"
  echo
  if [[ -n "${CLAUDE_CONFIG_DIR:-}" ]]; then
    echo "- \`CLAUDE_CONFIG_DIR\` is set (value hidden). Profiles may share or override this."
  else
    echo "- \`CLAUDE_CONFIG_DIR\` not set; default per-user config location is in use."
  fi
  echo "- CCP does not read or copy credentials, OAuth tokens, or Keychain data from any profile."
  echo
  echo "---"
  echo "_Generated by \`profile-doctor.sh\`._"
} | tee "$REPORT" >/dev/null

echo "Wrote $REPORT"
