#!/usr/bin/env bash
# setup-profiles.sh — create the `claude-team` and `claude-max` launchers used by
# the Change Claude Profile (ccp) workflow.
#
# Each launcher runs Claude Code with its own CLAUDE_CONFIG_DIR, so the two
# accounts (Teams/work and personal Max) keep isolated logins, settings, and
# plugins — without ever sharing credentials. The launchers are real executables
# (not shell aliases) on purpose: ccp's plugin-inventory calls `claude-team
# plugin list` from inside a script, and aliases don't exist in non-interactive
# shells.
#
# Platform: tested on macOS. Linux works too (identical mechanism). Windows is
# not supported yet — it would need .cmd/.ps1 shims and a different config path;
# the script exits cleanly there with guidance.
#
# Usage:
#   scripts/setup-profiles.sh                  # auto-detect install dir, create both
#   scripts/setup-profiles.sh --force          # overwrite existing launchers
#   INSTALL_DIR=~/.local/bin  scripts/setup-profiles.sh
#   TEAM_DIR=~/.claude-work MAX_DIR=~/.claude-personal scripts/setup-profiles.sh
#
# It never logs you in (that's interactive) and never touches credentials.

set -euo pipefail

FORCE=0
[[ "${1:-}" == "--force" ]] && FORCE=1

# --- platform guard ---
OS="$(uname -s)"
case "$OS" in
  Darwin) PLATFORM="macOS" ;;
  Linux)  PLATFORM="Linux" ;;
  *)
    echo "Unsupported platform: $OS." >&2
    echo "setup-profiles.sh currently supports macOS and Linux." >&2
    echo "On Windows, create wrappers that set CLAUDE_CONFIG_DIR before calling claude." >&2
    exit 1
    ;;
esac

# --- require claude on PATH ---
if ! command -v claude >/dev/null 2>&1; then
  echo "Error: 'claude' (Claude Code) was not found in PATH. Install Claude Code first." >&2
  exit 1
fi

# --- config dirs (override via env) ---
TEAM_DIR="${TEAM_DIR:-$HOME/.claude-team}"
MAX_DIR="${MAX_DIR:-$HOME/.claude-max}"

on_path() { case ":$PATH:" in *":$1:"*) return 0 ;; *) return 1 ;; esac; }

# --- choose an install dir that is in PATH and writable ---
choose_install_dir() {
  if [[ -n "${INSTALL_DIR:-}" ]]; then printf '%s' "$INSTALL_DIR"; return; fi
  local d
  for d in "/usr/local/bin" "$HOME/.local/bin" "$HOME/bin"; do
    if [[ -d "$d" && -w "$d" ]] && on_path "$d"; then printf '%s' "$d"; return; fi
  done
  # fallback: first writable candidate even if not on PATH (warned later)
  for d in "$HOME/.local/bin" "/usr/local/bin" "$HOME/bin"; do
    if [[ -d "$d" && -w "$d" ]]; then printf '%s' "$d"; return; fi
  done
  printf ''
}

DIR="$(choose_install_dir)"
if [[ -z "$DIR" ]]; then
  echo "Error: no writable bin directory found (/usr/local/bin, ~/.local/bin, ~/bin)." >&2
  echo "Set INSTALL_DIR=/some/dir and re-run." >&2
  exit 1
fi

write_launcher() {
  local name="$1" cfg_dir="$2" path="$DIR/$1"
  if [[ -e "$path" && "$FORCE" -ne 1 ]]; then
    echo "• $name already exists at $path (use --force to overwrite) — skipped."
    return
  fi
  cat > "$path" <<EOF
#!/usr/bin/env bash
# $name — launch Claude Code with an isolated profile (config dir: $cfg_dir).
# Generated by claude-code/scripts/setup-profiles.sh — safe to edit/regenerate.
exec env CLAUDE_CONFIG_DIR="$cfg_dir" claude "\$@"
EOF
  chmod +x "$path"
  echo "✓ wrote $path  (CLAUDE_CONFIG_DIR=$cfg_dir)"
}

echo "Platform   : $PLATFORM"
echo "Install dir: $DIR"
echo "Team config: $TEAM_DIR"
echo "Max config : $MAX_DIR"
echo
write_launcher claude-team "$TEAM_DIR"
write_launcher claude-max  "$MAX_DIR"
echo

if ! on_path "$DIR"; then
  echo "⚠  $DIR is not in your PATH. Add it, e.g.:"
  echo "     echo 'export PATH=\"$DIR:\$PATH\"' >> ~/.zshrc && source ~/.zshrc"
  echo
fi

cat <<'EOF'
Next steps:
  1. Log into each profile once (interactive — sign in with the right account):
       claude-team     # Teams / work account
       claude-max      # personal Max account
  2. Verify both respond:
       claude-team --version && claude-max --version
  3. In a repo, hand off and take over between them:
       (in claude-team)  /ccp:handoff
       (open the same repo in claude-max)  /ccp:takeover
  4. Align plugins across profiles:
       /ccp:plugin-inventory  ->  /ccp:plugin-sync-plan  ->  /ccp:plugin-apply

This script created no accounts and touched no credentials.
EOF
